### PR TITLE
Update formatted_ext_patterns.tsv for issue #58

### PR DESCRIPTION
**Pull request by dustine32**

### CODE REVIEW

**Comment by dustine32** [comment]
@ukemi The positively_regulates and negatively_regulates rules should now be the same in this TSV. I could do some fancy RO subClassOf magic for managing these but right now I'm just dealing with them like strings.

Rerunning the bad_extensions report with these changes gives me the same file, no lines dropped.

**Comment by ukemi** [comment]
Rerunning the bad_extensions report with these changes gives me the same file, no lines dropped.

No, I just noticed it in this PR. I'm working on the other file.

**Comment by dustine32** [comment]
@ukemi Sorry, returning back to this PR. Does this mean I'm OK to merge these changes? Or do we need to add more to `formatted_ext_patterns.tsv` beyond the `positively_regulates` and `negatively_regulates` rules?

**Comment by dustine32** [comment]
@ukemi Great! Thank you!

**Pull request merged**
