### PR TITLE
Update formatted_ext_patterns.tsv

### PR DESCRIPTION
**Pull request by dustine32**
This should address all items in issue #68.

I'll generate new `bad_extensions` sheets for MGI and WB to see how these look.

### CODE REVIEW

**Comment by dustine32** [comment]
Sorry @ukemi I was too eager to click on an icon and it caused GH to re-request a review from you. I'll merge this PR at noon PST today if I don't hear any complaints. Thanks!

**Comment by ukemi** [comment]
No worries @dustine32. Today I went through the newest spreadsheet and fixed all the remaining annotation that had delimiter problems/cardianlity. There are still quite a few annotations that I think should pass, but maybe for some reason or another they still aren't covered by the rules. In the spreadsheet I have added a column at the left that indicates my assessment of the annotations. Let me know if you have any questions or concerns.

**Comment by dustine32** [comment]
@ukemi Here's the report regenerated after today's updates:
https://docs.google.com/spreadsheets/d/11imOaWoQBfn1X5xVT9XAmuCC-GBTyxaLZ8-0USMsgVQ/edit#gid=0

For some of the [rule changes](https://github.com/geneontology/gocamgen/commit/c7e093aae3e0d7827b219d323d4e60bfc2000c57#diff-92669ace3eb48a6d5edce962191e1505) I took the liberty of specifying regulation of biological process (GO:0050789) as the root term. We can change it if it's too broad.

**Comment by ukemi** [comment]
Looks like some of my annotation changes haven't percolated through the MGI release yet. But we are getting better with each run.

**Comment by ukemi** [comment]
Bringing the rule up to the level of Regulation of biological process will make the checks pass, but will also allow curators to use the chain relations with incorrect terms. @vanaukenk, what do you think?

**Pull request merged**
